// exchange calc - angular/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { CurrencyService } from '../services/Currency.service';
import { dateGenerator } from '../helpers/dateGenerator';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent implements OnInit {
  public currencies: any = [];
  currentDay = dateGenerator();

  constructor(private currencyService: CurrencyService) {}

  ngOnInit(): void {
    this.currencyService.getRates().subscribe({
      next: (res) => {
        this.currencies = filterCurrency(res);
      },
      error: (e) => console.error(e),
    });
  }
}

function filterCurrency(array: any) {
  return array.filter((currency: { ccy: string }) => currency.ccy !== 'BTC');
}

<header class="header">
  <h2>Курс валют по состоянию на {{currentDay}}</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Валюта</th>
        <th scope="col">Покупка</th>
        <th scope="col">Продажа</th>
      </tr>
    </thead>
    <tbody *ngFor="let currency of currencies">
      <tr>
        <th>{{currency.ccy}}</th>
        <td>{{currency.buy}}</td>
        <td>{{currency.sale}}</td>
      </tr>
    </tbody>
  </table>
</header>

// exchange calc - react/src/components/Header/Header.jsx
import React from "react";
import "./header.css";
import { v4 as uuidv4 } from "uuid";
import { cutTheNumber } from "../../helpers/cutTheNumber";
import { dateGenerator } from "../../helpers/dateGenerator";

const Header = ({ rates }) => {
  let currentDate = dateGenerator();
  return (
    <header className="header">
      <h2>Курс валют по состоянию на {currentDate}</h2>
      <table className="table">
        <thead>
          <tr>
            <th scope="col">Валюта</th>
            <th scope="col">Покупка</th>
            <th scope="col">Продажа</th>
          </tr>
        </thead>
        <tbody>
          {rates.map((currency) => {
            return (
              <tr key={uuidv4()}>
                <th scope="row">{currency.ccy}</th>
                <td>{cutTheNumber(currency.buy)}</td>
                <td>{cutTheNumber(currency.sale)}</td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </header>
  );
};

export default Header;
